### ISSUE TITLE
SMBusWrapper obselete

### ISSUE THREAD

**Issue by imwatson** [Seeed-Studio/Seeed_Python_SGP30#1]
**Describe the bug**
SMbusWrapper is no longer used in smbus2 - calling it gives an error.

**To Reproduce**
1. Follow wiki instructions
2. You'll see an error stating that sgp30.py cannot import SMBusWrapper from smbus2

**Expected behavior**
Code should run to produce CO2 value

**Screenshots**

**Desktop (please complete the following information):**
Raspberry Pi4

**Smartphone (please complete the following information):**
Debian latest build (30/12/21)

**Additional context**
Solution here: 
https://github.com/kplindegaard/smbus2/blob/master/CHANGELOG.md

**Comment by baorepo** [comment]
@is-qian  please update this API

**Comment by is-qian** [comment]
Thank you for your reminder, SMbusWrapper is no longer used in this repository.
